[workspace]
resolver = "2"
members = [
    "crates/redsuite-core",
    "redline",
    "redshift",
    "redhat",
    "programs/redline",
    "programs/redshift",
    "programs/redhat",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Magicblock Labs <dev@magicblock.gg>"]

[workspace.dependencies]
redsuite-core = { path = "crates/redsuite-core" }

tokio = { version = "1", features = ["rt", "macros", "time"] }
async-trait = "0.1"

serde = { version = "1", features = ["derive"] }
json = { package = "sonic-rs", version = "0.5" }
rand = "0.8"

pubkey = { package = "solana-pubkey", version = "2" }
keypair = { package = "solana-keypair", version = "2" }
signature = { package = "solana-signature", version = "2" }
instruction = { package = "solana-instruction", version = "2" }
account = { package = "solana-account", version = "2" }

solana-program = "2.2"
