[package]
name = "redsuite-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }

serde = { workspace = true }
json = { workspace = true }
rand = { workspace = true }

pubkey = { workspace = true }
keypair = { workspace = true }
signature = { workspace = true }
instruction = { workspace = true }
account = { workspace = true }
