[package]
name = "redsuite-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }

serde = { workspace = true }
json = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }

pubkey = { workspace = true }
keypair = { workspace = true }
signature = { workspace = true }
instruction = { workspace = true }
account = { workspace = true }
signer = { workspace = true }
hash = { workspace = true }
transaction = { workspace = true }
bincode = { workspace = true }
