[package]
name = "redline-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pubkey = { workspace = true }
instruction = { workspace = true }
sdk-ids = { workspace = true }
sdk = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
sha2 = { workspace = true }
