[package]
name = "redshift-program"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["schedulecommit"]
schedulecommit = [
    "dep:borsh",
    "dep:sdk",
    "dep:sdk-ids",
    "dep:magic-api",
    "dep:bincode",
]
upgraded = []

[dependencies]
redshift-interface = { workspace = true }
redline-interface = { workspace = true }
borsh = { workspace = true, optional = true }
sdk = { workspace = true, optional = true }
solana-program = { workspace = true }
sdk-ids = { workspace = true, optional = true }
magic-api = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
