[package]
name = "redshift-program"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["schedulecommit"]
schedulecommit = ["dep:borsh", "dep:sdk", "dep:solana-sdk-ids"]
upgraded = []
no-entrypoint = []

[dependencies]
borsh = { workspace = true, optional = true }
sdk = { workspace = true, optional = true }
solana-program = { workspace = true }
solana-sdk-ids = { version = "3", optional = true }
