[package]
name = "redline"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
redsuite-core = { workspace = true }
redline-interface = { workspace = true }
futures-util = { workspace = true }
instruction = { workspace = true }
pubkey = { workspace = true }
keypair = { workspace = true }
signer = { workspace = true }
sdk-ids = { workspace = true }
signature = { workspace = true }

[dev-dependencies]
