[package]
name = "redline"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
redsuite-core = { workspace = true }
redline-program = { workspace = true }
pubkey = { workspace = true }
keypair = { workspace = true }
signer = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
