[package]
name = "redshift"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
redsuite-core = { workspace = true }
redline-program = { workspace = true }
instruction = { workspace = true }
pubkey = { workspace = true }
keypair = { workspace = true }
signer = { workspace = true }
json = { workspace = true }

[dev-dependencies]

[[test]]
name = "example"
path = "tests/harness/example.rs"

[[test]]
name = "api_invariants"
path = "tests/harness/api_invariants.rs"

[[test]]
name = "claim_fees"
path = "tests/committor/claim_fees.rs"

[[test]]
name = "pubsub_contracts"
path = "tests/pubsub/pubsub_contracts.rs"

[[test]]
name = "clone_on_access"
path = "tests/chainlink/clone_on_access.rs"

[[test]]
name = "commit_roundtrip"
path = "tests/committor/commit_roundtrip.rs"
