[package]
name = "redshift"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
redsuite-core = { workspace = true }
redline-interface = { workspace = true }
redshift-interface = { workspace = true }
instruction = { workspace = true }
pubkey = { workspace = true }
hash = { workspace = true }
transaction = { workspace = true }
keypair = { workspace = true }
signature = { workspace = true }
signer = { workspace = true }
solana-commitment-config = "3.1"
solana-transaction-status-client-types = "4.1"
sdk-ids = { workspace = true }
base64 = { workspace = true }
serde_json = "1"
solana-account-decoder-client-types = "4.1"
json = { workspace = true }
rand = { workspace = true }
rusqlite = { workspace = true }
solana-address-lookup-table-interface = { version = "3.0", features = ["bincode", "bytemuck"] }
sdk = { workspace = true, features = ["spl", "modular-sdk"] }

[dev-dependencies]
