[package]
name = "redshift-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
borsh = { workspace = true }
solana-program = { workspace = true }
sdk = { workspace = true }
solana-sdk-ids = "3"
magic-api = { package = "magicblock-magic-program-api", version = "0.10.1", default-features = false }
bincode = { workspace = true }
