[package]
name = "redshift-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
borsh = { workspace = true }
pubkey = { workspace = true }
instruction = { workspace = true }
sdk-ids = { workspace = true }
solana-program-error = { workspace = true }
sdk = { workspace = true }
magic-api = { workspace = true }
bincode = { workspace = true }
