[package]
name = "redhat"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true }
redsuite-core = { workspace = true }
redshift-program = { workspace = true, features = ["no-entrypoint"] }
redhat-program = { workspace = true, features = ["no-entrypoint"] }
instruction = { workspace = true }
pubkey = { workspace = true }
keypair = { workspace = true }
signer = { workspace = true }

[dev-dependencies]

[[test]]
name = "illegal_writable"
path = "tests/chainlink/illegal_writable.rs"

[[test]]
name = "fee_payer_rules"
path = "tests/aperture/fee_payer_rules.rs"
