[package]
name = "redhat"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true }
redsuite-core = { workspace = true }
redshift-interface = { workspace = true }
redhat-interface = { workspace = true }
instruction = { workspace = true }
pubkey = { workspace = true }
keypair = { workspace = true }
signer = { workspace = true }

[dev-dependencies]
